### ISSUE TITLE
error en espacio entre el = y el > en el get del api

### ISSUE THREAD

**Issue by javalenciacai** [javalenciacai/ejerciciogitapi#8]
![image](https://github.com/javalenciacai/ejerciciogitapi/assets/25663630/b4af6a10-de39-466e-a836-62a0a6df843d)
Se evidencia que al realizar la compilacion sale error :
![image](https://github.com/javalenciacai/ejerciciogitapi/assets/25663630/9c314993-b947-471a-8385-f0d22d269885)
y no logra compilar

resultado esperado que el sistema inicie el api y quede escuchando

**Comment by leydierazo** [comment]
Se corrige el bug con el PR https://github.com/javalenciacai/ejerciciogitapi/pull/9
